CREATE TABLE "TEST"."CUSTOMER" 
   (	"ID" VARCHAR2(10), 
	"NAME" VARCHAR2(50), 
	"CONTACT" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100), 
	"RMID" VARCHAR2(10)
   )


   CREATE TABLE "TEST"."BANK_EMPLOYEE" 
   (	"ID" VARCHAR2(10), 
	"NAME" VARCHAR2(50), 
	"CONTACT" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100)
   )


CREATE TABLE "TEST"."CUSTOMER_LOCATION" 
   (  "CUSTID" VARCHAR2(10), 
  "DISTANCE" NUMBER(25,0), 
  "SCHEDULED" VARCHAR2(1), 
  "RMID" VARCHAR2(10),
  "APPOINTMENTNEEDED" VARCHAR2(1) 
   );


CREATE TABLE "TEST"."APPOINTMENTS" 
   (  "CUSTID" VARCHAR2(10), 
  "STARTTIME" DATE, 
  "ENDTIME" DATE, 
  "RMID" VARCHAR2(100),
    "COMMENTS" VARCHAR2(100),
    "LAST_UPDATE_DATE" DATE
   );


   http://localhost:8080//gap/bookappointment/c1/222/Y

   http://localhost:8080//gap/confirmAppointmentd/c1/r1/yes